version: '3'
services:
  squid:
    container_name: 'squid-proxy'
    image: sameersbn/squid
    restart: always
    environment:
      - SQUID_CACHE_DIR=/var/spool/squid/cache
    ports:
      - 13128:3128
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
  privoxy:
    container_name: 'privoxy-proxy'
    build: ./privoxy/
    restart: always
    ports:
      - 18118:8118
    volumes:
      - ./privoxy/config:/etc/privoxy/config
